language: r
cache: packages
os: linux

addons:
  apt:
    packages:
      - poppler-utils

r_binary_packages:
  - covr

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=verbose

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
